const mainSection = [
  {
    src: "https://akcdn.detik.net.id/visual/2023/03/29/drama-korea-duty-after-school-2023_169.jpeg?w=650&q=90",
    title: "",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
];

const continueMovies = [
  {
    src: "https://jeurnals.b-cdn.net/wp-content/uploads/DLU-cover.jpeg",
    title: "Don't Look UP",
    rating: "4.9",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://asset.kompas.com/crops/fLFkvYIecWo1QtC2wHcCFV126TE=/0x5:1000x505/780x390/data/photo/2021/12/28/61cabe1bdc381.png",
    title: "ALL OF US ARE DEAD",
    rating: "4.8",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://www.lazone.id/storage/news/Januari_2023/03_Januari/Movie/orig-blue%20lock-cover.jpg",
    title: "Blue Lock",
    rating: "4.7",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://imgx.sonora.id/crop/0x0:0x0/x/photo/2023/07/24/aaaabbr_ni4lpwefiuryqcin3_tkyq9f-20230724023712.jpg",
    title: "A Man Called Otto",
    rating: "4.5",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://assets.kompasiana.com/items/album/2023/07/19/suzume-64b75bf3a0688f4fad71e093.jpg?t=o&v=740&x=416",
    title: "Suzume",
    rating: "4.9",
    episodes: "",
    genres: ["", "", ""],
  },
];

const topMovies = [
  {
    src: "https://images.plex.tv/photo?size=large-1280&url=https%3A%2F%2Fmetadata-static.plex.tv%2F6%2Fgracenote%2F6712d44cade77919f9365b7626aa37d7.jpg",
    title: "suzume",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/akurat/images/2023/03/big/img_64195ea53c50e0-97937540-78580199.JPG",
    title: "jurrasic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BODRlNTY5ZjktZjE0Ni00YjZhLTk3NTItYzk0ZjYxN2QxMWEzXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_.jpg",
    title: "sonic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero-6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/id/f/f4/The_Little_Mermaid_%282023_film%29.png",
    title: "litle-mermaid",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://images.justwatch.com/poster/309791505/s718/duty-after-school.jpg",
    title: "duty-after-school",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://cdn0-production-images-kly.akamaized.net/Z5gXiKOXZ0AaSHp8KgaTJSQ0_1o=/800x1066/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4334651/original/046648600_1677131777-20230223_125314.jpg",
    title: "missing",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "",
    title: "",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
];

const trendingMovies = [
  {
    src: "https://starzplay-img-prod-ssl.akamaized.net/474w/MGM/THETOMORROWWARY2021M/THETOMORROWWARY2021M-474x677-PST.jpg",
    title: "tomorrow-war",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BODZhNzlmOGItMWUyYS00Y2Q5LWFlNzMtM2I2NDFkM2ZkYmE1XkEyXkFqcGdeQXVyMTU5OTA4NTIz._V1_.jpg",
    title: "quantumania",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/id-guardiansofthegalaxy-vol3-payoffposter_6ba5c28b.jpeg",
    title: "gotg-3",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/id/8/80/A_Man_Called_Otto_poster.jpg",
    title: "otto",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/id/f/f4/The_Little_Mermaid_%282023_film%29.png",
    title: "litle-mermaid",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://images.plex.tv/photo?size=large-1280&url=https%3A%2F%2Fmetadata-static.plex.tv%2F6%2Fgracenote%2F6712d44cade77919f9365b7626aa37d7.jpg",
    title: "suzume",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/akurat/images/2023/03/big/img_64195ea53c50e0-97937540-78580199.JPG",
    title: "jurrasic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BODRlNTY5ZjktZjE0Ni00YjZhLTk3NTItYzk0ZjYxN2QxMWEzXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_.jpg",
    title: "sonic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero-6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
];

const newRelease = [
  {
    src: "https://upload.wikimedia.org/wikipedia/id/f/f4/The_Little_Mermaid_%282023_film%29.png",
    title: "litle-mermaid",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://images.justwatch.com/poster/309791505/s718/duty-after-school.jpg",
    title: "duty-after-school",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://cdn0-production-images-kly.akamaized.net/Z5gXiKOXZ0AaSHp8KgaTJSQ0_1o=/800x1066/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4334651/original/046648600_1677131777-20230223_125314.jpg",
    title: "missing",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "",
    title: "",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://images.plex.tv/photo?size=large-1280&url=https%3A%2F%2Fmetadata-static.plex.tv%2F6%2Fgracenote%2F6712d44cade77919f9365b7626aa37d7.jpg",
    title: "suzume",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/akurat/images/2023/03/big/img_64195ea53c50e0-97937540-78580199.JPG",
    title: "jurrasic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BODRlNTY5ZjktZjE0Ni00YjZhLTk3NTItYzk0ZjYxN2QxMWEzXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_.jpg",
    title: "sonic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero-6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
];

export { topMovies, trendingMovies, newRelease, continueMovies, mainSection };
